/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.1.2
 * Product:       scd4x
 * Model-Version: 2.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "scd4x_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c.h"
#include "sensirion_i2c_hal.h"
#include "itm.h"

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

#define ROUND(x) ((int32_t)((x) + 0.5))

static uint8_t communication_buffer[9] = {0};

static uint8_t _i2c_address;
static bool _measurement_running = false;

typedef struct {
    const scd41_context_t* context;
    scd4x_runtime_fault_cause_t cause;
    int16_t error;
    uint32_t hal_state;
    uint32_t hal_error;
    uint32_t repeat_count;
    bool has_active_fault;
    bool line_open;
} scd4x_itm_fault_log_state_t;

static bool g_scd4x_itm_short_log_enabled = true;
static scd4x_itm_fault_log_state_t g_scd4x_itm_fault_log_state = {0};
/* Guard mutex da bi xoa bo — chi dung config->i2c_mutex (MutexI2C1Handle) de serialize.
 * Thiet ke guard chi can thiet khi co nhieu SCD41 instance tren nhieu task khac nhau.
 * Du an nay: 1 instance, 1 task → MutexI2C1 la du. */

static int16_t scd4x_runtime_lock(const scd41_config_t* config) {
    if ((config == NULL) || (config->i2c_mutex == NULL)) {
        return NOT_IMPLEMENTED_ERROR;
    }

    if (osMutexAcquire(config->i2c_mutex, osWaitForever) != osOK) {
        return NOT_IMPLEMENTED_ERROR;
    }

    return NO_ERROR;
}

static void scd4x_runtime_unlock(const scd41_config_t* config) {
    if ((config != NULL) && (config->i2c_mutex != NULL)) {
        (void)osMutexRelease(config->i2c_mutex);
    }
}

static void scd4x_runtime_update_diag(const scd41_config_t* config,
                                      scd41_context_t* context) {
    if ((config == NULL) || (context == NULL) || (config->i2c_handle == NULL)) {
        return;
    }

    context->i2c_hal_state = (uint32_t)HAL_I2C_GetState(config->i2c_handle);
    context->i2c_hal_error = HAL_I2C_GetError(config->i2c_handle);
}

static scd4x_runtime_fault_cause_t scd4x_runtime_classify_fault(
    const scd41_context_t* context, int16_t error) {
    uint32_t hal_error = 0U;

    if (context != NULL) {
        hal_error = context->i2c_hal_error;
    }

    if (error == NO_ERROR) {
        return SCD4X_RUNTIME_FAULT_NONE;
    }

    /* NOT_IMPLEMENTED_ERROR (31) = loi RTOS noi bo (mutex/heap), KHONG phai loi I2C. */
    if (error == (int16_t)NOT_IMPLEMENTED_ERROR) {
        return SCD4X_RUNTIME_FAULT_RTOS;
    }

    if ((error == (int16_t)HAL_TIMEOUT) || ((hal_error & HAL_I2C_ERROR_TIMEOUT) != 0U)) {
        return SCD4X_RUNTIME_FAULT_TIMEOUT;
    }

    if ((error == (int16_t)HAL_BUSY)) {
        return SCD4X_RUNTIME_FAULT_BUSY;
    }

    if ((hal_error & HAL_I2C_ERROR_AF) != 0U) {
        return SCD4X_RUNTIME_FAULT_NO_ACK;
    }

    if ((hal_error & (HAL_I2C_ERROR_BERR | HAL_I2C_ERROR_ARLO | HAL_I2C_ERROR_OVR)) != 0U) {
        return SCD4X_RUNTIME_FAULT_BUS;
    }

    if (error == CRC_ERROR) {
        return SCD4X_RUNTIME_FAULT_CRC;
    }

    if (error == (int16_t)HAL_ERROR) {
        return SCD4X_RUNTIME_FAULT_NO_ACK;
    }

    return SCD4X_RUNTIME_FAULT_UNKNOWN;
}

static void scd4x_runtime_notify(const scd41_config_t* config,
                                 const scd41_context_t* context,
                                 scd4x_runtime_event_t event) {
    if ((context != NULL) && (context->on_event != NULL)) {
        context->on_event(config, context, event, context->on_event_context);
    }
}

static const char* scd4x_runtime_fault_cause_to_text(
    scd4x_runtime_fault_cause_t cause) {
    switch (cause) {
        case SCD4X_RUNTIME_FAULT_NONE:
            return "NONE";
        case SCD4X_RUNTIME_FAULT_NO_ACK:
            return "NO_ACK";
        case SCD4X_RUNTIME_FAULT_TIMEOUT:
            return "TIMEOUT";
        case SCD4X_RUNTIME_FAULT_BUS:
            return "BUS_ERROR";
        case SCD4X_RUNTIME_FAULT_CRC:
            return "CRC_ERROR";
        case SCD4X_RUNTIME_FAULT_BUSY:
            return "BUSY";
        case SCD4X_RUNTIME_FAULT_RTOS:
            return "RTOS_ERROR";        default:
            return "UNKNOWN";
    }
}

static const char* scd4x_runtime_error_to_text(int16_t error) {
    switch (error) {
        case NO_ERROR:
            return "NO_ERROR";
        case CRC_ERROR:
            return "CRC_ERROR";
        case I2C_BUS_ERROR:
            return "I2C_BUS_ERROR";
        case I2C_NACK_ERROR:
            return "I2C_NACK_ERROR";
        case BYTE_NUM_ERROR:
            return "BYTE_NUM_ERROR";
        default:
            break;
    }

    if (error == (int16_t)HAL_ERROR) {
        return "HAL_ERROR";
    }
    if (error == (int16_t)HAL_BUSY) {
        return "HAL_BUSY";
    }
    if (error == (int16_t)HAL_TIMEOUT) {
        return "HAL_TIMEOUT";
    }

    return "UNMAPPED_ERROR";
}

static const char* scd4x_runtime_i2c_state_to_text(uint32_t state) {
    switch ((HAL_I2C_StateTypeDef)state) {
        case HAL_I2C_STATE_RESET:
            return "RESET";
        case HAL_I2C_STATE_READY:
            return "READY";
        case HAL_I2C_STATE_BUSY:
            return "BUSY";
        case HAL_I2C_STATE_BUSY_TX:
            return "BUSY_TX";
        case HAL_I2C_STATE_BUSY_RX:
            return "BUSY_RX";
        case HAL_I2C_STATE_LISTEN:
            return "LISTEN";
        case HAL_I2C_STATE_BUSY_TX_LISTEN:
            return "BUSY_TX_LISTEN";
        case HAL_I2C_STATE_BUSY_RX_LISTEN:
            return "BUSY_RX_LISTEN";
        case HAL_I2C_STATE_ABORT:
            return "ABORT";
        case HAL_I2C_STATE_TIMEOUT:
            return "TIMEOUT";
        case HAL_I2C_STATE_ERROR:
            return "ERROR";
        default:
            return "UNKNOWN";
    }
}

static void scd4x_runtime_print_i2c_error_flags(uint32_t hal_error) {
    bool first = true;

    if (hal_error == HAL_I2C_ERROR_NONE) {
        itm_print("NONE");
        return;
    }

    if ((hal_error & HAL_I2C_ERROR_BERR) != 0U) {
        itm_print("BERR");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_ARLO) != 0U) {
        itm_print(first ? "ARLO" : "|ARLO");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_AF) != 0U) {
        itm_print(first ? "NACK(AF)" : "|NACK(AF)");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_OVR) != 0U) {
        itm_print(first ? "OVR" : "|OVR");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_DMA) != 0U) {
        itm_print(first ? "DMA" : "|DMA");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_TIMEOUT) != 0U) {
        itm_print(first ? "TIMEOUT" : "|TIMEOUT");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_SIZE) != 0U) {
        itm_print(first ? "SIZE" : "|SIZE");
        first = false;
    }

    if (first) {
        itm_print("UNKNOWN_FLAGS");
    }
}

static const char* scd4x_runtime_fault_hint(scd4x_runtime_fault_cause_t cause) {
    switch (cause) {
        case SCD4X_RUNTIME_FAULT_NO_ACK:
            return "check sensor power/address/wiring";
        case SCD4X_RUNTIME_FAULT_TIMEOUT:
            return "check SDA/SCL disconnected or bus stuck";
        case SCD4X_RUNTIME_FAULT_BUS:
            return "check noise/short on I2C lines";
        case SCD4X_RUNTIME_FAULT_CRC:
            return "data corrupted, check cable/noise";
        case SCD4X_RUNTIME_FAULT_BUSY:
            return "check sensor power/wiring - SDA may be stuck low (no pull-ups when sensor removed)";
        case SCD4X_RUNTIME_FAULT_RTOS:
            return "check i2c_mutex is set in scd41_config and RTOS is running";
        default:
            return "check sensor connection";
    }
}

static const char* scd4x_runtime_bus_to_text(const scd41_config_t* config) {
    if ((config == NULL) || (config->i2c_handle == NULL) ||
        (config->i2c_handle->Instance == NULL)) {
        return "I2C";
    }

    if (config->i2c_handle->Instance == I2C1) {
        return "I2C1";
    }
    if (config->i2c_handle->Instance == I2C2) {
        return "I2C2";
    }

    return "I2C";
}

static const char* scd4x_runtime_fault_simple_text(
    scd4x_runtime_fault_cause_t cause) {
    switch (cause) {
        case SCD4X_RUNTIME_FAULT_NO_ACK:
            return "khong giao tiep duoc voi sensor (NACK)";
        case SCD4X_RUNTIME_FAULT_TIMEOUT:
            return "timeout bus, sensor khong phan hoi";
        case SCD4X_RUNTIME_FAULT_BUS:
            return "loi truyen thong bus";
        case SCD4X_RUNTIME_FAULT_CRC:
            return "du lieu loi (CRC), giao tiep khong on dinh";
        case SCD4X_RUNTIME_FAULT_BUSY:
            return "bus I2C bi ket - co the mat nguon hoac mat day cam bien";
        case SCD4X_RUNTIME_FAULT_RTOS:
            return "loi RTOS: i2c_mutex chua duoc gan hoac acquire that bai";
        default:
            return "mat ket noi sensor";
    }
}

void scd4x_runtime_default_itm_set_short_log(bool enable) {
    g_scd4x_itm_short_log_enabled = enable;
    g_scd4x_itm_fault_log_state.context = NULL;
    g_scd4x_itm_fault_log_state.repeat_count = 0U;
    g_scd4x_itm_fault_log_state.has_active_fault = false;
    g_scd4x_itm_fault_log_state.line_open = false;
}

void scd4x_runtime_default_itm_event_handler(const scd41_config_t* config,
                                             const scd41_context_t* context,
                                             scd4x_runtime_event_t event,
                                             void* user_context) {
    bool same_fault;

    (void)user_context;

    if (context == NULL) {
        return;
    }

    switch (event) {
        case SCD4X_RUNTIME_EVENT_FAULT:
            same_fault = g_scd4x_itm_fault_log_state.has_active_fault &&
                         (g_scd4x_itm_fault_log_state.context == context) &&
                         (g_scd4x_itm_fault_log_state.cause == context->fault_cause) &&
                         (g_scd4x_itm_fault_log_state.error == context->error) &&
                         (g_scd4x_itm_fault_log_state.hal_state == context->i2c_hal_state) &&
                         (g_scd4x_itm_fault_log_state.hal_error == context->i2c_hal_error);

            if (same_fault) {
                g_scd4x_itm_fault_log_state.repeat_count++;
            } else {
                g_scd4x_itm_fault_log_state.context = context;
                g_scd4x_itm_fault_log_state.cause = context->fault_cause;
                g_scd4x_itm_fault_log_state.error = context->error;
                g_scd4x_itm_fault_log_state.hal_state = context->i2c_hal_state;
                g_scd4x_itm_fault_log_state.hal_error = context->i2c_hal_error;
                g_scd4x_itm_fault_log_state.repeat_count = 1U;
                g_scd4x_itm_fault_log_state.has_active_fault = true;
            }

            if (g_scd4x_itm_short_log_enabled && same_fault) {
                break;
            }

            if (g_scd4x_itm_short_log_enabled) {
                itm_print("[SCD41][ERR] ");
                itm_print(scd4x_runtime_bus_to_text(config));
                itm_print(": ");
                itm_print(scd4x_runtime_fault_simple_text(context->fault_cause));
                itm_print(".\r\n");
                break;
            }

            itm_print("[SCD41][FAULT] cause=");
            itm_print(scd4x_runtime_fault_cause_to_text(context->fault_cause));
            itm_print("(");
            itm_put_int((int)context->fault_cause);
            itm_print(")");
            itm_print(", err=");
            itm_print(scd4x_runtime_error_to_text(context->error));
            itm_print("(");
            itm_put_int((int)context->error);
            itm_print(")");
            itm_print(", state=");
            itm_print(scd4x_runtime_i2c_state_to_text(context->i2c_hal_state));
            itm_print("(");
            itm_put_int((int)context->i2c_hal_state);
            itm_print(")");
            itm_print(", hal_error=");
            scd4x_runtime_print_i2c_error_flags(context->i2c_hal_error);
            itm_print("(");
            itm_put_int((int)context->i2c_hal_error);
            itm_print(")");
            itm_print(", hint=");
            itm_print(scd4x_runtime_fault_hint(context->fault_cause));
            itm_print(", count=");
            itm_put_int((int)g_scd4x_itm_fault_log_state.repeat_count);
            itm_print("\r\n");
            break;

        case SCD4X_RUNTIME_EVENT_RECOVERED: {
            uint32_t n = g_scd4x_itm_fault_log_state.repeat_count;
            scd4x_runtime_fault_cause_t prev_cause = g_scd4x_itm_fault_log_state.cause;
            g_scd4x_itm_fault_log_state.has_active_fault = false;
            g_scd4x_itm_fault_log_state.repeat_count = 0U;
            itm_print("[SCD41] ");
            itm_print(scd4x_runtime_bus_to_text(config));
            itm_print(": da ket noi lai sensor");
            if (n > 1U) {
                itm_print(" (sau ");
                itm_put_int((int)n);
                itm_print(" lan loi ");
                itm_print(scd4x_runtime_fault_cause_to_text(prev_cause));
                itm_print(")");
            }
            itm_print("\r\n");
            break;
        }

        case SCD4X_RUNTIME_EVENT_RESTART_ATTEMPT:
            if (!g_scd4x_itm_short_log_enabled) {
                itm_print("[SCD41] retry start periodic measurement\r\n");
            }
            break;

        default:
            break;
    }
}

void scd4x_runtime_set_event_callback(const scd41_config_t* config,
                                      scd41_context_t* context,
                                      scd4x_runtime_event_callback_t callback,
                                      void* user_context) {
    (void)config;

    if (context == NULL) {
        return;
    }

    context->on_event = callback;
    context->on_event_context = user_context;
}

void scd4x_init(uint8_t i2c_address) {
    _i2c_address = i2c_address;
}

void scd4x_runtime_init(scd41_config_t* config,
                        scd41_context_t* context) {
    if ((config == NULL) || (context == NULL)) {
        return;
    }

    if (config->i2c_address == 0U) {
        config->i2c_address = SCD41_I2C_ADDR_62;
    }
    if (config->restart_after_failures == 0U) {
        config->restart_after_failures = 5U;
    }

    context->co2 = 0;
    context->temperature_m_deg_c = 0;
    context->humidity_m_percent_rh = 0;
    context->data_ready = false;
    context->error = NO_ERROR;
    context->i2c_hal_state = 0U;
    context->i2c_hal_error = 0U;
    context->consecutive_error_count = 0U;
    context->total_error_count = 0U;
    context->fault_active = false;
    context->fault_cause = SCD4X_RUNTIME_FAULT_NONE;
    context->on_event = NULL;
    context->on_event_context = NULL;

    sensirion_i2c_hal_set_handle(config->i2c_handle);
    sensirion_i2c_hal_set_mutex(config->i2c_mutex);
    scd4x_init(config->i2c_address);
    scd4x_runtime_update_diag(config, context);
}

int16_t scd4x_runtime_start_periodic_measurement(const scd41_config_t* config,
                                                 scd41_context_t* context) {
    if ((config == NULL) || (context == NULL) || (config->i2c_handle == NULL) ||
        (config->i2c_mutex == NULL)) {
        return NOT_IMPLEMENTED_ERROR;
    }

    context->error = scd4x_runtime_lock(config);
    if (context->error != NO_ERROR) {
        return context->error;
    }

    sensirion_i2c_hal_set_handle(config->i2c_handle);
    sensirion_i2c_hal_set_mutex(config->i2c_mutex);
    scd4x_init(config->i2c_address);

    context->error = scd4x_start_periodic_measurement();
    scd4x_runtime_unlock(config);

    scd4x_runtime_update_diag(config, context);
    if (context->error == NO_ERROR) {
        context->consecutive_error_count = 0U;
    }

    return context->error;
}

int16_t scd4x_runtime_read_if_ready(const scd41_config_t* config,
                                    scd41_context_t* context) {
    if ((config == NULL) || (context == NULL) || (config->i2c_handle == NULL) ||
        (config->i2c_mutex == NULL)) {
        return NOT_IMPLEMENTED_ERROR;
    }

    context->error = scd4x_runtime_lock(config);
    if (context->error != NO_ERROR) {
        return context->error;
    }

    sensirion_i2c_hal_set_handle(config->i2c_handle);
    sensirion_i2c_hal_set_mutex(config->i2c_mutex);
    scd4x_init(config->i2c_address);

    context->error = scd4x_get_data_ready_status(&context->data_ready);
    if (context->error != NO_ERROR) {
        scd4x_runtime_unlock(config);
        scd4x_runtime_update_diag(config, context);
        return context->error;
    }

    if (!context->data_ready) {
        scd4x_runtime_unlock(config);
        scd4x_runtime_update_diag(config, context);
        return NO_ERROR;
    }

    context->error = scd4x_read_measurement(&context->co2,
                                            &context->temperature_m_deg_c,
                                            &context->humidity_m_percent_rh);
    scd4x_runtime_unlock(config);
    scd4x_runtime_update_diag(config, context);
    return context->error;
}

bool scd4x_runtime_poll(const scd41_config_t* config, scd41_context_t* context) {
    int16_t restart_error;
    bool fault_was_active;

    if ((config == NULL) || (context == NULL)) {
        return false;
    }

    fault_was_active = context->fault_active;
    scd4x_runtime_fault_cause_t fault_cause_snapshot = context->fault_cause;
    context->error = scd4x_runtime_read_if_ready(config, context);
    if (context->error == NO_ERROR) {
        /* After a disconnect/power-loss fault (NOT CRC), force start command once bus is alive again.
         * CRC errors must NOT trigger a restart: the sensor is still measuring normally.
         * Sending START while sensor is in periodic mode causes a NACK → bus recovery →
         * I2C peripheral DeInit/Init → further CRC errors on subsequent reads (feedback loop). */
        if (fault_was_active && !context->data_ready &&
            fault_cause_snapshot != SCD4X_RUNTIME_FAULT_CRC) {
            _measurement_running = false;
            (void)scd4x_runtime_start_periodic_measurement(config, context);
            context->error = scd4x_runtime_read_if_ready(config, context);
        }

        if (context->error != NO_ERROR) {
            context->total_error_count++;
            context->consecutive_error_count++;
            context->fault_cause = scd4x_runtime_classify_fault(context, context->error);
            context->fault_active = true;
            scd4x_runtime_notify(config, context, SCD4X_RUNTIME_EVENT_FAULT);
            return false;
        }

        context->consecutive_error_count = 0U;
        context->fault_cause = SCD4X_RUNTIME_FAULT_NONE;

        if (context->fault_active) {
            context->fault_active = false;
            scd4x_runtime_notify(config, context, SCD4X_RUNTIME_EVENT_RECOVERED);
        }

        return context->data_ready;
    }

    context->total_error_count++;
    context->consecutive_error_count++;
    context->fault_cause = scd4x_runtime_classify_fault(context, context->error);

    if (context->fault_cause != SCD4X_RUNTIME_FAULT_CRC) {
        _measurement_running = false;
    }

    if (!context->fault_active) {
        context->fault_active = true;
        scd4x_runtime_notify(config, context, SCD4X_RUNTIME_EVENT_FAULT);
    } else {
        /* Notify again on each fault to allow caller-specific policies. */
        scd4x_runtime_notify(config, context, SCD4X_RUNTIME_EVENT_FAULT);
    }

    if ((config->restart_after_failures > 0U) &&
        ((context->consecutive_error_count % config->restart_after_failures) == 0U)) {
        scd4x_runtime_notify(config, context, SCD4X_RUNTIME_EVENT_RESTART_ATTEMPT);
        restart_error = scd4x_runtime_start_periodic_measurement(config, context);
        if (restart_error == NO_ERROR) {
            context->consecutive_error_count = 0U;
        }
    }

    return false;
}

bool Scd41Api_Service(const scd41_config_t* config,
                      scd41_context_t* context,
                      osMessageQueueId_t queue,
                      scd4x_runtime_event_callback_t on_event) {
    scd41_queue_item_t item;

    if ((queue == NULL) || (config == NULL) || (context == NULL)) {
        return false;
    }

    /* Set callback once on first run, or when caller changes callback/context. */
    if ((context->on_event != on_event) ||
        (context->on_event_context != (void*)context)) {
        scd4x_runtime_set_event_callback(config, context, on_event, (void*)context);
    }

    if (!scd4x_runtime_poll(config, context)) {
        return false;
    }

    item.co2 = context->co2;
    item.temperature_m_deg_c = context->temperature_m_deg_c;
    item.humidity_m_percent_rh = context->humidity_m_percent_rh;

    return (osMessageQueuePut(queue, &item, 0U, 0U) == osOK);
}

uint16_t scd4x_signal_co2_concentration(uint16_t raw_co2_concentration) {
    uint16_t co2_concentration = 0;
    co2_concentration = raw_co2_concentration;
    return co2_concentration;
}

uint32_t scd4x_signal_ambient_pressure(uint16_t raw_ambient_pressure) {
    uint32_t ambient_pressure = 0;
    ambient_pressure = (uint32_t)raw_ambient_pressure * 100;
    return ambient_pressure;
}

int16_t scd4x_set_ambient_pressure(uint32_t ambient_pressure) {
    int16_t local_error = 0;
    uint16_t raw_ambient_pressure = (uint16_t)ROUND(ambient_pressure / 100.0);
    local_error = scd4x_set_ambient_pressure_raw(raw_ambient_pressure);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    return local_error;
}

int16_t scd4x_get_ambient_pressure(uint32_t* a_ambient_pressure) {
    uint16_t raw_ambient_pressure = 0;
    int16_t local_error = 0;
    local_error = scd4x_get_ambient_pressure_raw(&raw_ambient_pressure);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *a_ambient_pressure = scd4x_signal_ambient_pressure(raw_ambient_pressure);

    return local_error;
}

int16_t scd4x_get_data_ready_status(bool* arg_0) {
    uint16_t data_ready_status = 0;
    int16_t local_error = 0;
    local_error = scd4x_get_data_ready_status_raw(&data_ready_status);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *arg_0 = (data_ready_status & 2047) != 0;
    ;
    return local_error;
}

int16_t scd4x_get_sensor_variant(scd4x_sensor_variant* a_sensor_variant) {
    scd4x_sensor_variant ret_val = SCD4X_SENSOR_VARIANT_MASK;
    uint16_t raw_sensor_variant = 0;
    uint16_t my_sensor_variant = 0;
    int16_t local_error = 0;
    ret_val = SCD4X_SENSOR_VARIANT_MASK;
    uint16_t mask = (uint16_t)(ret_val);
    local_error = scd4x_get_sensor_variant_raw(&raw_sensor_variant);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    my_sensor_variant = (uint16_t)(raw_sensor_variant & mask);
    if (my_sensor_variant == (uint16_t)(SCD4X_SENSOR_VARIANT_SCD40)) {
        ret_val = SCD4X_SENSOR_VARIANT_SCD40;
    } else if (my_sensor_variant == (uint16_t)(SCD4X_SENSOR_VARIANT_SCD41)) {
        ret_val = SCD4X_SENSOR_VARIANT_SCD41;
    } else if (my_sensor_variant == (uint16_t)(SCD4X_SENSOR_VARIANT_SCD42)) {
        ret_val = SCD4X_SENSOR_VARIANT_SCD42;
    } else if (my_sensor_variant == (uint16_t)(SCD4X_SENSOR_VARIANT_SCD43)) {
        ret_val = SCD4X_SENSOR_VARIANT_SCD43;
    }
    *a_sensor_variant = ret_val;
    return local_error;
}

int16_t scd4x_start_periodic_measurement() {
    if (_measurement_running) {
        return NO_ERROR;
    }

    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x21b1);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }

    //in ra itmconsole----------------------------------------------------------------------------------------------------------------
    itm_print("[SCD41] START_PERIODIC_MEASUREMENT");
    itm_print("\r\n");
    //--------------------------------------------------------------------------------------------------------------------------------


    _measurement_running = true;
    return local_error;
}

int16_t scd4x_read_measurement_raw(uint16_t* co2_concentration,
                                   uint16_t* temperature,
                                   uint16_t* relative_humidity) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xec05);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 6);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *co2_concentration = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *temperature = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    *relative_humidity = sensirion_common_bytes_to_uint16_t(&buffer_ptr[4]);
    return local_error;
}

int16_t scd4x_read_measurement(uint16_t* co2, int32_t* temperature_m_deg_c,
                               int32_t* humidity_m_percent_rh) {
    int16_t error;
    uint16_t temperature;
    uint16_t humidity;
    error = scd4x_read_measurement_raw(co2, &temperature, &humidity);
    if (error) {
        return error;
    }
    *temperature_m_deg_c = ((21875 * (int32_t)temperature) >> 13) - 45000;
    *humidity_m_percent_rh = ((12500 * (int32_t)humidity) >> 13);
    return NO_ERROR;
}

int16_t scd4x_stop_periodic_measurement() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3f86);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(500 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_set_temperature_offset_raw(uint16_t offset_temperature) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x241d);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, offset_temperature);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_temperature_offset_raw(uint16_t* offset_temperature) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2318);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *offset_temperature = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_sensor_altitude(uint16_t sensor_altitude) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2427);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, sensor_altitude);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_sensor_altitude(uint16_t* sensor_altitude) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2322);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *sensor_altitude = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_ambient_pressure_raw(uint16_t ambient_pressure) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xe000);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, ambient_pressure);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_ambient_pressure_raw(uint16_t* ambient_pressure) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xe000);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *ambient_pressure = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_perform_forced_recalibration(uint16_t target_co2_concentration,
                                           uint16_t* frc_correction) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x362f);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, target_co2_concentration);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(400 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *frc_correction = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_automatic_self_calibration_enabled(uint16_t asc_enabled) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2416);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, asc_enabled);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_automatic_self_calibration_enabled(uint16_t* asc_enabled) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2313);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *asc_enabled = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_automatic_self_calibration_target(uint16_t asc_target) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x243a);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, asc_target);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_automatic_self_calibration_target(uint16_t* asc_target) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x233f);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *asc_target = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_start_low_power_periodic_measurement() {
    if (_measurement_running) {
        return NO_ERROR;
    }

    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x21ac);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    _measurement_running = true;
    return local_error;
}

int16_t scd4x_get_data_ready_status_raw(uint16_t* data_ready_status) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xe4b8);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *data_ready_status = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_persist_settings() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3615);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(800 * 1000);
    return local_error;
}

int16_t scd4x_get_serial_number(uint16_t* serial_number,
                                uint16_t serial_number_size) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3682);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 6);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_common_copy_bytes(&buffer_ptr[0], (uint8_t*)serial_number,
                                (serial_number_size * 2));
    return local_error;
}

int16_t scd4x_perform_self_test(uint16_t* sensor_status) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3639);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10000 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *sensor_status = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_perform_factory_reset() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3632);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1200 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_reinit() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3646);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(30 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_get_sensor_variant_raw(uint16_t* sensor_variant) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x202f);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *sensor_variant = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_measure_single_shot() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x219d);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5000 * 1000);
    return local_error;
}

int16_t scd4x_measure_single_shot_rht_only() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2196);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(50 * 1000);
    return local_error;
}

int16_t scd4x_power_down() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x36e0);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_wake_up() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x36f6);
    sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    sensirion_i2c_hal_sleep_usec(30 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_set_automatic_self_calibration_initial_period(
    uint16_t asc_initial_period) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2445);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, asc_initial_period);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_automatic_self_calibration_initial_period(
    uint16_t* asc_initial_period) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2340);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *asc_initial_period = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_automatic_self_calibration_standard_period(
    uint16_t asc_standard_period) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x244e);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, asc_standard_period);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_automatic_self_calibration_standard_period(
    uint16_t* asc_standard_period) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x234b);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *asc_standard_period = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}
